# Generated by Django 4.1.3 on 2022-11-24 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('show_count', models.BigIntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('liked_users', models.ManyToManyField(related_name='liked_tweets', to=settings.AUTH_USER_MODEL)),
                ('parent_tweet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtweets', to='tweet.tweet')),
                ('quoted_tweet', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweet.tweet')),
                ('retweeted_users', models.ManyToManyField(related_name='retweets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
