# Generated by Django 4.1.3 on 2022-11-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_author_blockeds'),
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
        migrations.AddField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_tweets', to='user.author'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweeted_users',
            field=models.ManyToManyField(related_name='retweets', to='user.author'),
        ),
    ]
