# Generated by Django 4.1.1 on 2022-11-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_remove_tweet_user_tweet_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created']},
        ),
    ]
