# Generated by Django 4.1.1 on 2022-11-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_alter_tweet_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='quoted_tweet',
        ),
    ]
