# Generated by Django 4.1.1 on 2022-11-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_remove_tweet_quoted_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='parent_tweet',
        ),
    ]
