# Generated by Django 4.1.1 on 2022-11-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_remove_tweet_parent_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent_tweet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtweets', to='tweet.tweet'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='quoted_tweet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweet.tweet'),
        ),
    ]
