# Generated by Django 4.1.3 on 2022-11-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='blockeds',
            field=models.ManyToManyField(related_name='from_blockeds', to='user.author'),
        ),
    ]
