# Generated by Django 4.1.1 on 2022-11-29 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_author_blockeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='blockeds',
        ),
    ]
