# Generated by Django 4.1.1 on 2022-11-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_author_blockeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='blockeds',
            field=models.ManyToManyField(to='user.author'),
        ),
    ]
