# Generated by Django 4.1.3 on 2022-12-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_author_blockeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
